[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pygame_automata"
version = "0.1.0"
description = "Cellular automata with Pygame interface"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Jesper Anteryd", email = "jesper.anteryd@proton.me"},
]
keywords = ["cellular automata", "pygame"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Games/Entertainment",
    "Topic :: Creative",
]
dependencies = [
    "numpy>=2.5",
    "pygame>=2.6",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4",
    "pre_commit>=4.6.1"
]

[project.urls]
Repository = "https://github.com/Dyretna/pygame_automata"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
